### PR TITLE
[Cu-kz52j4] Desktop list view - fix problems with overflow + Loading state spinner 

### PR DESCRIPTION
**Pull request by eastemployeer**
Fixed all problems with overflowing text and icons and problem with different size cards (As you can see in the image below. Cards have same sizes)

Zrzut ekranu z 2021-06-03 23-44-00
Zrzut ekranu z 2021-06-03 23-44-09

### CODE REVIEW

**Comment by Zummek** [comment]
Task linked: [CU-kz52j4 Desktop list view - fix problems with overflow](https://app.clickup.com/t/kz52j4)

**Comment by Zummek** [comment]
Looking to images in descriptions, 
1. I think left and right margin of item are different. I suggest reducing right padding to have more space for name. 
2. We should limit to one line of avatars, by using `MultipleUsersAvatars` component 
3. > ... problem with different size cards (As you can see in the image below. Cards have same sizes)

      Did you try on page with `pageSize` bigger than 2?

If is beyond the scope of this task, we can note these suggestions in backlog task: https://app.clickup.com/t/ht2ujw

**Comment by eastemployeer** [comment]
1. No they are not different. Screenshots are just not equal size....It wasn't very hard to spot on the images.
2. I think 2 lines of avatars look better. This is not objective attention.
3. Yes. Everything working correctly

**Comment by Zummek** [comment]
> 1. No they are not different. Screenshots are just not equal size....It wasn't very hard to spot on the images.
> 2. I think 2 lines of avatars look better. This is not objective attention.
> 3. Yes. Everything working correctly

1. I mean paddings of items of list, not of page
image
3. I suggest to increase page size in this PR if it's working now

**Review by Buglik — COMMENTED** [review]
1) I think icon is a bit too narrow (looks a little cramped from the left side, at least in my opinion)
2)  Isn't the space between cards in col-12 situation  too big ? (pic below) 
3) I think we agreed at some point about not showing all avatars, just like in ```MultipleUsersAvatars``` component. I might be wrong but i do remember sth about it.
Now some of them just dissapear when they don't fit. Would look better when showed "+3" in that kind of situation (again that's my personal opinion)

image

**Comment by eastemployeer** [comment]
1. No it's not. It looks like this because there is no splitter between icon and text. Check first and then make an attention.
2. Maybe a little.
3. No time to play with this type of behaviour. It's icon, not text, and that's why simple text-oveflow is not enough. Yes they disappear, this is the best behaviour for icons that look good.

**ATTENTION!!!**
I checked and everything is centered properly. Don't say to me that "you think someting is not centered". I don't have time to check it for you. If you checked and it's not centered, then I will fix it. Otherwise I won't do anything about it. From this time on, I won't even respond to your comment.

**Comment by eastemployeer** [comment]
> 1. I mean paddings of items of list, not of page
>    image

For example this type of comment is ridiculous.  What is wrong with it?
1. @Zummek  didn't check anything before making this comment. I advise you to run this site and check in the browser if this distances are really not equal. If not, check why. 
2. Really? Do you want me to check every view and every line of code to spot something like @Zummek spotted in this picture? Not to mention that thing that he spotted is actually nothing wrong... I've spotted numerous of more serious 'features' as @Zummek  likes to call them in your code and mostly I didn't say a thing about it because I know the most important thing is to merge changes first. Then make fixes...
3. When looking at this comment it makes me laugh... and not only me.

**Comment by Buglik** [comment]
TBH i dont know why u react this way,
that's front-end task and if i open it up in a browser before checking out any code and see sth i don't like shouldn't i write about it hmm?
Components may be centered and everything, doesn't mean they look perfect to us and that's what we wrote here, our opinions about the looks. Our REVIEW, right?
You don't agree with us? ok, maybe tell us why you've done so? maybe we're wrong? but comments like your "attention"? rly 
And the thing about "features", i agree that sometimes merge fast then fix but wasn't this task supposed to be the fix?

**Comment by eastemployeer** [comment]
Can't wait to see your coming PR's :)

**Review by PrzemekRychter — APPROVED** [review]
Great!

**Pull request merged**
